In [2]:
import numpy as np
import pandas as pd

### Comparison Operators

In [3]:
x = np.array([1,2,3])

In [4]:
x

array([1, 2, 3])

In [5]:
x1 = np.array([[1,2,3],
              [4,5,6]])

In [6]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
x > x1

array([[False, False, False],
       [False, False, False]])

In [9]:
x >= x1

array([[ True,  True,  True],
       [False, False, False]])

In [11]:
bool_arr = x >=x1
bool_arr

array([[ True,  True,  True],
       [False, False, False]])

In [12]:
type(bool_arr), bool_arr.dtype

(numpy.ndarray, dtype('bool'))

In [13]:
x1 > 5

array([[False, False, False],
       [False, False,  True]])

In [14]:
x1 == x1 

array([[ True,  True,  True],
       [ True,  True,  True]])

### More on
 - https://www.tutorialgateway.org/python-numpy-comparison-operators/
 - https://numpy.org/doc/stable/reference/routines.ma.html