In [2]:
import numpy as np
import pandas as pd

## Sorting an Array

In [4]:
random_arr = np.random.randint(10, size = (3,5))
random_arr

array([[5, 4, 7, 4, 1],
       [4, 3, 9, 6, 9],
       [2, 5, 6, 7, 4]])

In [5]:
random_arr.shape

(3, 5)

In [9]:
# Sort() function: sort() function sorts the values row-wise here
np.sort(random_arr)

array([[1, 4, 4, 5, 7],
       [3, 4, 6, 9, 9],
       [2, 4, 5, 6, 7]])

In [11]:
# Return the indices that would sort an array
np.argsort(random_arr)

array([[4, 1, 3, 0, 2],
       [1, 0, 3, 2, 4],
       [0, 4, 1, 2, 3]], dtype=int64)

In [13]:
x1 = np.array([1,2,3])

In [14]:
x1

array([1, 2, 3])

In [16]:
np.argsort(x1)

array([0, 1, 2], dtype=int64)

In [17]:
# Return the min value from an array
np.argmin(x1)

0

In [19]:
# Return the max value from an array
np.argmax(x1)

2

In [20]:
# Return the max value from an array
np.argmax(random_arr)

7

In [25]:
random_arr

array([[5, 4, 7, 4, 1],
       [4, 3, 9, 6, 9],
       [2, 5, 6, 7, 4]])

In [27]:
# Return the max value from an array using axis = 0
np.argmax(random_arr, axis = 0)

array([0, 2, 1, 2, 1], dtype=int64)

In [29]:
# Return the max value from an array using axis = 1
np.argmax(random_arr, axis = 1)

array([2, 2, 3], dtype=int64)