In [5]:
import numpy as np
import pandas as pd

## Exercies

#### Dot Product   (Butter Sales)

In [4]:
np.random.seed(0)
# Number of Jars
sales_amount = np.random.randint(20,  size = (5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [8]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, index= ["Mon", "Tue", "Wed", "Thurs", "Fri"],
                           columns= ["Almond_Butter", "Peanut_Butter", "Cashew_Butter"])
weekly_sales

Almond_Butter  Peanut_Butter  Cashew_Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [9]:
# Create Price Array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [11]:
# Create butter_prices Dataframe
butter_prices = pd.DataFrame(prices, 
                            index = ["Price"],
                            columns= ["Almond_Butter", "Peanut_Butter", "Cashew_Butter"])
butter_prices


# Show an error

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [14]:
# To resolve this problem, reshape the price

# Create butter_prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), 
                            index = ["Price"],
                            columns= ["Almond_Butter", "Peanut_Butter", "Cashew_Butter"])
butter_prices

Almond_Butter  Peanut_Butter  Cashew_Butter
Price             10              8             12

In [16]:
prices

array([10,  8, 12])

In [17]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [19]:
# Shape are not aliged , so Transpose it
total_sales  = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [20]:
# Create_daily_sales
butter_prices

Almond_Butter  Peanut_Butter  Cashew_Butter
Price             10              8             12

In [21]:
# Weekly_sales
weekly_sales

Almond_Butter  Peanut_Butter  Cashew_Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [22]:
weekly_sales.T.shape

(3, 5)

In [23]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [24]:
daily_sales

Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [25]:
weekly_sales

Almond_Butter  Peanut_Butter  Cashew_Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [26]:
weekly_sales["Total ($)"] = daily_sales.T

In [27]:
weekly_sales

Almond_Butter  Peanut_Butter  Cashew_Butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142